### ISSUE TITLE
credentials.jsonに関する記述がREADMEにない

### ISSUE THREAD

**Issue by HansRobo** [5ebec/piranhabon#2]
アプリを正常に実行するにはcredentials.jsonが必要なようですがREADMEに記述がありません．
credentials.jsonの取得方法も含めた記述があると分かりやすくなると思います！

※暇をみてPRを作るかも知れないです．

**Comment by h3y6e** [comment]
Issue & PR ありがとうございます！書かないとなぁと思いながら放置しておりました．

**Comment by h3y6e** [comment]
Mergeしました👍
